#### Function to generate fake DNI in Spanish Format

In [2]:
def fake_dni():
    # Generate eight random numbers
    random_numbers = ''.join(random.choices(string.digits, k=8))

    # Generate a random letter
    random_letter = random.choice(string.ascii_letters).upper()

    # Combine the random numbers and random letter
    random_id = random_numbers + random_letter

    return random_id

In [4]:
# Import Libraries
from faker import Faker
import datetime
import pandas as pd
import random
import string


fake = Faker('es_ES')

# Define the start and end dates
start_date = datetime.datetime(2022, 1, 1)
end_date = datetime.datetime(2022, 12, 31)


# Give % weights to values
values = ["Vivienda", "Oficina"]
weights = [0.8, 0.2] 


# Generate fake data
data = []
for _ in range(100):
    DNI = fake_dni()
    housing = random.choices(values, weights=weights)[0]
    age = fake.random_int(min=25, max=60)
    name = fake.first_name()
    surname = fake.last_name()
    alarms_off = fake.random_int(min=1, max=15)
    # salary = fake.random_int(min=30000, max=100000)
    date = fake.date_time_between(start_date=start_date, end_date=end_date).strftime("%d-%m-%Y")
    data.append([DNI,housing,age, name, surname,date,alarms_off])                                 

# Create DataFrame
df = pd.DataFrame(data, columns=['DNI',"Housing","Age",'Name', 'Surname', 'Date',"Alarms Off"])

df

          DNI   Housing  Age         Name     Surname        Date  Alarms Off
0   57440120Q   Oficina   46      Socorro        Jove  21-11-2022           6
1   35228655U  Vivienda   54        Vidal      Angulo  03-06-2022           9
2   68822361W  Vivienda   55      Petrona        Vega  16-12-2022           5
3   66957102B   Oficina   58      Haroldo    Clemente  27-10-2022          12
4   39007691O   Oficina   52      Antonia       Baena  05-05-2022           1
..        ...       ...  ...          ...         ...         ...         ...
95  48562702U  Vivienda   57       Roxana    Carrillo  23-11-2022          14
96  36739779T  Vivienda   47     Maricela        Toro  27-01-2022          15
97  24115912I  Vivienda   41         Dora      Perera  28-05-2022          11
98  05129911M  Vivienda   53  Julio César        Báez  01-12-2022           7
99  39922429Z  Vivienda   46     Federico  Villanueva  29-11-2022           3

[100 rows x 7 columns]